const socketActionsBlueprint = {
  CREATE_ROOM: 'CREATE-ROOM',
  NEW_ROOM: 'NEW-ROOM',
  JOIN_ROOM: 'JOIN-ROOM',
  WAITING_FOR_PLAYER_TWO: 'WAIT-FOR-PLAYER-TWO',
  ATTACK_SHIP: 'ATTACK-SHIP',
  ATTACK_SHIP_HANDLER: 'ATTACK-SHIP-HANDLER',
};
