export const roomActionTypes = {
  CREATE_ROOM: 'CREATE_ROOM',
  OPPONENT_JOINS: 'OPPONENT_JOINS',
};

export const gameActionTypes = {
  SET_PLAYER_ONE: 'SET-PLAYER-ONE',
  SET_PLAYER_TWO: 'SET-PLAYER-TWO',
  OPPONENT_JOINS: 'OPPONENT_JOINS',
};
